# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Web3 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm install
    - run: npx truffle compile
    - run: npx truffle test
    - run: cat ./TEST-results.xml
    - name: Test Reporting
      uses: phoenix-actions/test-reporting@v6
      id: test-report               # Set ID reference for step
      if: success() || failure()    # run this step even if previous step failed
      with:
          name: JEST Tests            # Name of the check run which will be created
          path: TEST-results.xml      # Path to test results
          reporter: jest-junit        # Format of test results
    
